=== fborrmann/memory_game/XSLT/game_states.dtd
<!ELEMENT games (game)*>
<!ELEMENT game (flippedCard, active_player_id, players, cards)>
<!ATTLIST game
			id CDATA #REQUIRED
			game_state (active | finished) #REQUIRED>
<!ELEMENT flippedCard (#PCDATA)>
<!ELEMENT active_player_id (#PCDATA)>
<!ELEMENT players (player+)>
<!ELEMENT player (name, points)>
<!ATTLIST player id CDATA #REQUIRED>
<!ELEMENT points (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST cards scale_factor CDATA #REQUIRED>
<!ELEMENT card (position_x, position_y)>
<!ELEMENT position_x (#PCDATA)>
<!ELEMENT position_y (#PCDATA)>
<!ATTLIST card card_state (shown | hidden) #REQUIRED
      id CDATA #REQUIRED
      pair CDATA #REQUIRED>

=== fborrmann/memory_game/game_states/game_states.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="svg_creator.xsl"?>
<!DOCTYPE game SYSTEM "game_states.dtd">
<games>
  <game id="0" game_state="active">
    <flippedCard>0</flippedCard>
    <active_player_id>1</active_player_id>
    <players>
      <player id="1">
		<name>Hans</name>
        <points>0</points>
		</player>
      <player id="2">
        <name>Jens</name>
        <points>2</points>
      </player>
    </players>
    <cards scale_factor="4.5">
      <card id="1" pair="1" card_state="shown">
        <position_x>10</position_x>
        <position_y>10</position_y>
      </card>
      <card id="2" pair="1" card_state="shown">
        <position_x>31</position_x>
        <position_y>10</position_y>
      </card>
      <card id="3" pair="2" card_state="shown">
        <position_x>10</position_x>
        <position_y>31</position_y>
      </card>
      <card id="4" pair="2" card_state="hidden">
        <position_x>31</position_x>
        <position_y>31</position_y>
      </card>
    </cards>
  </game>
</games>

=== fborrmann/memory_game/game_states/game_state1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE game SYSTEM "game_states.dtd">

<game game_state = "active">
	<active_player_id> 1 </active_player_id>
	<players>
		<player id="1">
			<name> Flo </name>
			<points> 2 </points> 
		</player>
		<player id="2">
			<name> Jens </name>
			<points> 1 </points>
		</player>
	</players>
	<cards scale_factor = "2">
		<card id = "1" card_state = "shown">
			<position_x> 200 </position_x>
			<position_y> 50 </position_y>
		</card>
		<card id = "1" card_state = "shown">
			<position_x> 350 </position_x>
			<position_y>  50 </position_y>
		</card>
		<card id = "2" card_state = "shown">
			<position_x> 200 </position_x>
			<position_y> 200 </position_y>
		</card>
		<card id = "2" card_state = "hidden">
			<position_x> 350 </position_x>
			<position_y> 200 </position_y>
		</card>
	</cards>
	
	
</game>
